name: gallery
description: A resource to help developers evaluate and use Flutter.
repository: https://github.com/flutter/gallery
version: 2.10.0+021000

environment:
  flutter: ^3.1.0-0 # Kept relatively close to master channel version
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_breakpoints: ^0.1.1
  animations: ^2.0.2
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  dual_screen: ^1.0.3
  flutter_gallery_assets: ^1.0.2
  flutter_localized_locales: ^2.0.3
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: ^3.0.1
  intl: ^0.17.0
  meta: ^1.7.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  provider: ^6.0.2
  rally_assets: ^3.0.1
  scoped_model: ^2.0.0
  shared_preferences: ^2.0.15
  shrine_images: ^2.0.1
  url_launcher: ^6.1.2
  vector_math: ^2.1.2
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ">=0.3.0+1 <0.5.0"
  uuid: ^3.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  args: ^2.3.1
  flutter_lints: ^2.0.1
  grinder: ^0.9.1
  path: ^1.8.1
  string_scanner: ^1.1.0
  test: ^1.21.1
  web_benchmarks: ^0.1.0

flutter:

  assets:
    - packages/flutter_gallery_assets/assets/studies/shrine_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/starter_card.png
    - packages/flutter_gallery_assets/assets/studies/starter_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/fortnightly_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/reply_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/fortnightly_card.png
    - packages/flutter_gallery_assets/assets/studies/crane_card.png
    - packages/flutter_gallery_assets/assets/studies/shrine_card.png
    - packages/flutter_gallery_assets/assets/studies/crane_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/rally_card.png
    - packages/flutter_gallery_assets/assets/studies/reply_card.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/material/material.png
    - packages/flutter_gallery_assets/assets/icons/reference/reference.png
    - packages/flutter_gallery_assets/assets/demos/bottom_navigation_background.png
    - packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoMono-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-ExtraBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-BoldItalic.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Thin.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-SemiBold.ttf
    - packages/flutter_gallery_assets/fortnightly/fortnightly_army.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_bees.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_chart.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_fabrics.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_feminists.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_gas.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_healthcare.jpg
    - packages/flutter_gallery_assets/fortnightly/fortnightly_stocks.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_title.png
    - packages/flutter_gallery_assets/fortnightly/fortnightly_war.png
    - packages/flutter_gallery_assets/reply/attachments/paris_1.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_2.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_3.jpg
    - packages/flutter_gallery_assets/reply/attachments/paris_4.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_0.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_1.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_2.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_3.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_4.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_5.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_6.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_7.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_8.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_9.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_10.jpg
    - packages/flutter_gallery_assets/reply/avatars/avatar_express.png
    - packages/flutter_gallery_assets/reply/icons/twotone_add_circle_outline.png
    - packages/flutter_gallery_assets/reply/icons/twotone_delete.png
    - packages/flutter_gallery_assets/reply/icons/twotone_drafts.png
    - packages/flutter_gallery_assets/reply/icons/twotone_error.png
    - packages/flutter_gallery_assets/reply/icons/twotone_folder.png
    - packages/flutter_gallery_assets/reply/icons/twotone_forward.png
    - packages/flutter_gallery_assets/reply/icons/twotone_inbox.png
    - packages/flutter_gallery_assets/reply/icons/twotone_send.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star_on_background.png
    - packages/flutter_gallery_assets/reply/icons/twotone_star.png
    - packages/flutter_gallery_assets/reply/icons/twotone_stars.png
    - packages/flutter_gallery_assets/reply/reply_logo.png
    - packages/flutter_gallery_assets/places/india_chennai_flower_market.png
    - packages/flutter_gallery_assets/places/india_thanjavur_market.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple.png
    - packages/flutter_gallery_assets/places/india_pondicherry_salt_farm.png
    - packages/flutter_gallery_assets/places/india_chennai_highway.png
    - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
    - packages/flutter_gallery_assets/places/india_chettinad_produce.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_technology.png
    - packages/flutter_gallery_assets/places/india_pondicherry_beach.png
    - packages/flutter_gallery_assets/places/india_pondicherry_fisherman.png
    - packages/flutter_gallery_assets/placeholders/avatar_logo.png
    - packages/flutter_gallery_assets/placeholders/placeholder_image.png
    - packages/flutter_gallery_assets/splash_effects/splash_effect_1.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_2.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_3.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_4.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_5.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_6.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_7.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_8.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_9.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_10.gif
    - packages/rally_assets/logo.png
    - packages/rally_assets/thumb.png
    - packages/shrine_images/diamond.png
    - packages/shrine_images/slanted_menu.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg
    - packages/shrine_images/7-0.jpg
    - packages/shrine_images/8-0.jpg
    - packages/shrine_images/9-0.jpg
    - packages/shrine_images/10-0.jpg
    - packages/shrine_images/11-0.jpg
    - packages/shrine_images/12-0.jpg
    - packages/shrine_images/13-0.jpg
    - packages/shrine_images/14-0.jpg
    - packages/shrine_images/15-0.jpg
    - packages/shrine_images/16-0.jpg
    - packages/shrine_images/17-0.jpg
    - packages/shrine_images/18-0.jpg
    - packages/shrine_images/19-0.jpg
    - packages/shrine_images/20-0.jpg
    - packages/shrine_images/21-0.jpg
    - packages/shrine_images/22-0.jpg
    - packages/shrine_images/23-0.jpg
    - packages/shrine_images/24-0.jpg
    - packages/shrine_images/25-0.jpg
    - packages/shrine_images/26-0.jpg
    - packages/shrine_images/27-0.jpg
    - packages/shrine_images/28-0.jpg
    - packages/shrine_images/29-0.jpg
    - packages/shrine_images/30-0.jpg
    - packages/shrine_images/31-0.jpg
    - packages/shrine_images/32-0.jpg
    - packages/shrine_images/33-0.jpg
    - packages/shrine_images/34-0.jpg
    - packages/shrine_images/35-0.jpg
    - packages/shrine_images/36-0.jpg
    - packages/shrine_images/37-0.jpg
    - lib/studies/shrine/assets/IMG_1187.JPG
    - lib/studies/shrine/assets/IMG_1188.JPG
    - lib/studies/shrine/assets/IMG_1189.JPG
    - lib/studies/shrine/assets/IMG_1192.JPG
    - lib/studies/shrine/assets/IMG_1238.JPG
    - lib/studies/shrine/assets/IMG_1240.JPG
    - lib/studies/shrine/assets/IMG_1285.JPG
    - lib/studies/shrine/assets/IMG_1291.JPG
    - lib/studies/shrine/assets/IMG_1292.JPG
    - lib/studies/shrine/assets/IMG_1299.JPG
    - lib/studies/shrine/assets/IMG_1301.JPG
    - lib/studies/shrine/assets/IMG_1306.JPG
    - lib/studies/shrine/assets/IMG_1309.JPG
    - lib/studies/shrine/assets/IMG_1315.JPG
    - lib/studies/shrine/assets/IMG_1486.JPG
    - lib/studies/shrine/assets/IMG_1495.JPG
    - lib/studies/shrine/assets/IMG_1497.JPG
    - lib/studies/shrine/assets/IMG_1498.JPG
    - lib/studies/shrine/assets/IMG_1499.JPG
    - lib/studies/shrine/assets/IMG_1506.JPG
    - lib/studies/shrine/assets/IMG_1515.JPG
    - lib/studies/shrine/assets/IMG_1540.JPG
    - lib/studies/shrine/assets/IMG_7652.JPG
    - lib/studies/shrine/assets/IMG_7666.JPG
    - lib/studies/shrine/assets/IMG_1728.JPG
    - lib/studies/shrine/assets/IMG_1730.JPG
    - lib/studies/shrine/assets/IMG_1730.MP4
    - lib/studies/shrine/assets/IMG_1732.JPG
    - lib/studies/shrine/assets/IMG_1733.JPG
    - lib/studies/shrine/assets/IMG_1734.JPG
    - lib/studies/shrine/assets/IMG_1771.JPG
    - lib/studies/shrine/assets/IMG_1771.MP4
    - lib/studies/shrine/assets/IMG_1774.JPG
    - lib/studies/shrine/assets/IMG_1774.MP4
    - lib/studies/shrine/assets/IMG_1777.JPG
    - lib/studies/shrine/assets/IMG_1783.JPG
    - lib/studies/shrine/assets/IMG_1783.MP4
    - lib/studies/shrine/assets/IMG_1784.JPG
    - lib/studies/shrine/assets/IMG_1785.JPG
    - lib/studies/shrine/assets/IMG_1785.MP4
    - lib/studies/shrine/assets/IMG_1796.JPG
    - lib/studies/shrine/assets/IMG_1796.MP4
    - lib/studies/shrine/assets/IMG_1797.JPG
    - lib/studies/shrine/assets/IMG_1797.MP4
    - lib/studies/shrine/assets/IMG_112.JPG
    - lib/studies/shrine/assets/IMG_2003.JPG
    - lib/studies/shrine/assets/IMG_486.JPG
    - lib/studies/shrine/assets/IMG_439.JPG
    - lib/studies/shrine/assets/IMG_2007.JPG
    - lib/studies/shrine/assets/IMG_2009.JPG
    - lib/studies/shrine/assets/IMG_2014.JPG
    - lib/studies/shrine/assets/IMG_2015.JPG
    - lib/studies/shrine/assets/IMG_2016.JPG
    - lib/studies/shrine/assets/IMG_2018.JPG
    - lib/studies/shrine/assets/IMG_2019.JPG
    - lib/studies/shrine/assets/IMG_2021.JPG
    - lib/studies/shrine/assets/IMG_2022.JPG
    - lib/studies/shrine/assets/IMG_2023.JPG
    - lib/studies/shrine/assets/IMG_2057.JPG
    - lib/studies/shrine/assets/IMG_2058.JPG
    - lib/studies/shrine/assets/IMG_2062.JPG
    - lib/studies/shrine/assets/IMG_2063.JPG
    - lib/studies/shrine/assets/IMG_2066.JPG
    - lib/studies/shrine/assets/IMG_1878.JPG
    - lib/studies/shrine/assets/IMG_1915.JPG
    - lib/studies/shrine/assets/IMG_1754.JPG
    - lib/studies/shrine/assets/IMG_2117.JPG
    - lib/studies/shrine/assets/IMG_2127.JPG
    - lib/studies/shrine/assets/IMG_2131.JPG
    - lib/studies/shrine/assets/IMG_2133.JPG
    - lib/studies/shrine/assets/IMG_2143.JPG
    - lib/studies/shrine/assets/IMG_2146.JPG
    - lib/studies/shrine/assets/IMG_155245.JPG
    - lib/studies/shrine/assets/IMG_155249.JPG
    - lib/studies/shrine/assets/IMG_43.JPG
    - lib/studies/shrine/assets/IMG_378.JPG
    - lib/studies/shrine/assets/IMG_413.JPG
    - lib/studies/shrine/assets/IMG_173600.JPG
    - lib/studies/shrine/assets/IMG_173930.JPG
    - lib/studies/merienda_tracker/assets/heart.png
    - lib/studies/merienda_tracker/assets/visited.png
    - lib/studies/merienda_tracker/assets/2.0x/heart.png
    - lib/studies/merienda_tracker/assets/2.0x/visited.png
  generate: true
  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
